import type { Metadata } from "next";
import { Playfair,Poppins} from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import Header from "@/components/Header";
import { Toaster } from "sonner";
// import ProtectedRoute from "@/contexts/ProtectRoute";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// const poppins = Poppins({
//   variable: "--font-poppins",
//   weight:["100","200","300","400","500","600","700","800","900"],
//   subsets : ["latin"]
// });
const playfair = Playfair({
  variable :"--font-playfair",
  weight :['300',"400","500","800"],
  subsets :["latin"]
})

// const geistMono = Geist_Mono({
//   variable: "--font-poppins",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.className} antialiased  overflow-x-hidden bg-white`}
      >
        <AuthProvider>
          <Toaster position="bottom-right"/>
          {/* <ProtectedRoute> */}
            <Header />

            {children}
          {/* </ProtectedRoute> */}
        </AuthProvider>
      </body>
    </html>
  );
}
