import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import Header from "@/components/Header";
import { Toaster } from "sonner";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Providers } from "@/components/providers/Provider";

// import ProtectedRoute from "@/contexts/ProtectRoute";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// const poppins = Poppins({
//   variable: "--font-poppins",
//   weight:["100","200","300","400","500","600","700","800","900"],
//   subsets : ["latin"]
// });
const lato = Lato({
  variable: "--font-lato",
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-poppins",
//   subsets: ["latin"],
// });
const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} antialiased  overflow-x-hidden bg-white`}
      >
          <Providers>
          <Header />
          {children}
        </Providers>
        {/* <AuthProvider>
          <QueryClientProvider client={queryClient}>
            <Toaster position="bottom-right" />
           
            <Header />

            {children}
          
          </QueryClientProvider>
        </AuthProvider> */}
      </body>
    </html>
  );
}
